/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package br.edu.ifsp.pep.visao;
import br.edu.ifsp.pep.dao.TipoVeiculoDAO;
import br.edu.ifsp.pep.modelo.TipoVeiculo;
import java.math.BigDecimal;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author bolhe
 */
public class TipoVeiculoView extends javax.swing.JDialog {
    
    private TipoVeiculoDAO tipoVeiculoDAO = new TipoVeiculoDAO();
    private List<TipoVeiculo> tiposVeiculos;
    private TipoVeiculo tipoveiculo; //ultilizando para inserir ou alterar
    
    /**
     * Creates new form TipoVeiculoView
     */
    public TipoVeiculoView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        this.setEnableCampoTexto(false);
        this.setEnabledBotoes(true);
    }
    
    private void setEnabledBotoes(boolean enable){
        bInserir.setEnabled(enable);
        bAlterar.setEnabled(enable);
        bExcluir.setEnabled(enable);
        bPesquisar.setEnabled(enable);
        bGravar.setEnabled(!enable);
        bCancelar.setEnabled(!enable);     
    }
    
    private void setEnableCampoTexto(boolean enable){
        tfNome.setEditable(enable);
        tfValorDiaria.setEnabled(enable);
        tfPesquisar.setEnabled(!enable);
        jTabela.setEnabled(!enable);
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pGeral = new javax.swing.JPanel();
        lTitulo = new javax.swing.JLabel();
        lNome = new javax.swing.JLabel();
        lValorDiaria = new javax.swing.JLabel();
        tfNome = new javax.swing.JTextField();
        tfValorDiaria = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabela = new javax.swing.JTable();
        pBotoes = new javax.swing.JPanel();
        bInserir = new javax.swing.JButton();
        bAlterar = new javax.swing.JButton();
        bExcluir = new javax.swing.JButton();
        bGravar = new javax.swing.JButton();
        bCancelar = new javax.swing.JButton();
        lNomePesquisar = new javax.swing.JLabel();
        tfPesquisar = new javax.swing.JTextField();
        bPesquisar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        pGeral.setBackground(new java.awt.Color(0, 255, 255));

        lTitulo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lTitulo.setForeground(new java.awt.Color(0, 0, 204));
        lTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lTitulo.setText("Tipos De Veículos");

        lNome.setText("Nome :");

        lValorDiaria.setText("Valor da Diaria :");

        tfNome.setBackground(new java.awt.Color(255, 255, 0));

        tfValorDiaria.setBackground(new java.awt.Color(255, 0, 255));
        tfValorDiaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfValorDiariaActionPerformed(evt);
            }
        });

        jTabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nome", "Valor da Diaria"
            }
        ));
        jTabela.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jTabela);

        pBotoes.setBackground(new java.awt.Color(51, 255, 51));
        pBotoes.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        bInserir.setBackground(new java.awt.Color(153, 153, 255));
        bInserir.setText("Inserir");
        bInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bInserirActionPerformed(evt);
            }
        });

        bAlterar.setBackground(new java.awt.Color(255, 255, 153));
        bAlterar.setText("Alterar");
        bAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAlterarActionPerformed(evt);
            }
        });

        bExcluir.setBackground(new java.awt.Color(255, 204, 255));
        bExcluir.setText("Excluir");
        bExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bExcluirActionPerformed(evt);
            }
        });

        bGravar.setBackground(new java.awt.Color(255, 204, 204));
        bGravar.setText("Gravar");
        bGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bGravarActionPerformed(evt);
            }
        });

        bCancelar.setBackground(new java.awt.Color(204, 255, 204));
        bCancelar.setText("Cancelar");
        bCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pBotoesLayout = new javax.swing.GroupLayout(pBotoes);
        pBotoes.setLayout(pBotoesLayout);
        pBotoesLayout.setHorizontalGroup(
            pBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bInserir)
                .addGap(82, 82, 82)
                .addComponent(bAlterar)
                .addGap(86, 86, 86)
                .addComponent(bExcluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                .addComponent(bGravar)
                .addGap(82, 82, 82)
                .addComponent(bCancelar)
                .addContainerGap())
        );
        pBotoesLayout.setVerticalGroup(
            pBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pBotoesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bInserir)
                    .addComponent(bAlterar)
                    .addComponent(bExcluir)
                    .addComponent(bGravar)
                    .addComponent(bCancelar))
                .addContainerGap())
        );

        lNomePesquisar.setText("Nome :");

        tfPesquisar.setBackground(new java.awt.Color(0, 153, 153));
        tfPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPesquisarActionPerformed(evt);
            }
        });

        bPesquisar.setBackground(new java.awt.Color(255, 153, 153));
        bPesquisar.setText("Pesquisar");
        bPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pGeralLayout = new javax.swing.GroupLayout(pGeral);
        pGeral.setLayout(pGeralLayout);
        pGeralLayout.setHorizontalGroup(
            pGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pGeralLayout.createSequentialGroup()
                .addGroup(pGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pGeralLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pGeralLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pBotoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pGeralLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(pGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lNome, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lValorDiaria, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lNomePesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(73, 73, 73)
                        .addGroup(pGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfNome)
                            .addComponent(tfValorDiaria)
                            .addComponent(tfPesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE))
                        .addGap(44, 44, 44)
                        .addComponent(bPesquisar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pGeralLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        pGeralLayout.setVerticalGroup(
            pGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pGeralLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lTitulo)
                .addGap(28, 28, 28)
                .addGroup(pGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lNome)
                    .addComponent(tfNome))
                .addGap(37, 37, 37)
                .addGroup(pGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lValorDiaria)
                    .addComponent(tfValorDiaria))
                .addGap(39, 39, 39)
                .addGroup(pGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lNomePesquisar)
                    .addComponent(tfPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bPesquisar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pGeral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pGeral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfValorDiariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfValorDiariaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfValorDiariaActionPerformed

    private void bAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAlterarActionPerformed

        if(jTabela.getSelectedRow() >= 0){
            this.setEnableCampoTexto(true);
            this.setEnabledBotoes(false);
        
            //carregar os dados para os cmapos de texto
            tipoveiculo = this.tiposVeiculos.get(jTabela.getSelectedRow());
            tfNome.setText(tipoveiculo.getNome());
            tfValorDiaria.setText(tipoveiculo.getValorDiaria().toString());
            
            tfNome.requestFocus();
        }else{
            JOptionPane.showMessageDialog(null,"Selecione um tipo de veiculo","Atenção",JOptionPane.WARNING_MESSAGE);
        }
        
        
    }//GEN-LAST:event_bAlterarActionPerformed

    private void bInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bInserirActionPerformed
        this.setEnableCampoTexto(true);
        this.setEnabledBotoes(false);
        
        tfNome.requestFocus();
        
    }//GEN-LAST:event_bInserirActionPerformed

    private void bGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGravarActionPerformed
        //inserir
        String nome = tfNome.getText();
        BigDecimal valorDiaria = new BigDecimal(tfValorDiaria.getText());
        String mensagem = "tipo veiculo cadastrado";
        if(nome.length() > 3){
            
            //adicionando
            if(tipoveiculo == null){
                tipoveiculo = new TipoVeiculo(nome, valorDiaria);
            }
            //alterando
            else{
                tipoveiculo.setNome(nome);
                tipoveiculo.setValorDiaria(valorDiaria);
                mensagem = "tipo veiculo alterado";
            }
            
            try {
                tipoVeiculoDAO.alterar(tipoveiculo);
                JOptionPane.showMessageDialog(null, mensagem);
                
                tfNome.setText("");
                tfValorDiaria.setText("");
                
                bPesquisarActionPerformed(evt);
                
                tipoveiculo = null;
                
                this.setEnabledBotoes(true);
                this.setEnableCampoTexto(false);
                
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Informe pelo menos 4 caracteres no campo nome.", "Atenção", JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_bGravarActionPerformed

    private void tfPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPesquisarActionPerformed

    private void bPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPesquisarActionPerformed
        tiposVeiculos = tipoVeiculoDAO.findByNome(tfPesquisar.getText());
        this.atualizarTabela();
    }//GEN-LAST:event_bPesquisarActionPerformed

    private void bExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bExcluirActionPerformed
        if(jTabela.getSelectedRow() >= 0){
            TipoVeiculo tipoVeiculoSelecionado = this.tiposVeiculos.get(jTabela.getSelectedRow());
            try {
                tipoVeiculoDAO.remover(tipoVeiculoSelecionado);
                JOptionPane.showMessageDialog(null, "tipo de veiculo selecionado foi excluido");    
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "O tipo de veiculo não pode ser excluido", "Alerta",JOptionPane.WARNING_MESSAGE);
            }
            
            this.bPesquisarActionPerformed(evt);
        }else{
            JOptionPane.showMessageDialog(null, "selecione um tipo de veiculo", "Alerta",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_bExcluirActionPerformed

    private void bCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelarActionPerformed
        tfNome.setText("");
        tfValorDiaria.setText("");
        this.setEnableCampoTexto(false);
        this.setEnabledBotoes(true);
    }//GEN-LAST:event_bCancelarActionPerformed

    private void atualizarTabela(){
        
        DefaultTableModel modelo = (DefaultTableModel) jTabela.getModel();
        modelo.setNumRows(0);
        for (TipoVeiculo tipoVeiculo : tiposVeiculos) {
            modelo.addRow(new Object[] {tipoVeiculo.getId(),tipoVeiculo.getNome(),tipoVeiculo.getValorDiaria()});
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TipoVeiculoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TipoVeiculoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TipoVeiculoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TipoVeiculoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TipoVeiculoView dialog = new TipoVeiculoView(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAlterar;
    private javax.swing.JButton bCancelar;
    private javax.swing.JButton bExcluir;
    private javax.swing.JButton bGravar;
    private javax.swing.JButton bInserir;
    private javax.swing.JButton bPesquisar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTabela;
    private javax.swing.JLabel lNome;
    private javax.swing.JLabel lNomePesquisar;
    private javax.swing.JLabel lTitulo;
    private javax.swing.JLabel lValorDiaria;
    private javax.swing.JPanel pBotoes;
    private javax.swing.JPanel pGeral;
    private javax.swing.JTextField tfNome;
    private javax.swing.JTextField tfPesquisar;
    private javax.swing.JTextField tfValorDiaria;
    // End of variables declaration//GEN-END:variables
}
